services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./exports:/app/exports
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
